version: '3'

services:
  prirosfront:
    image: priros-node-pnpm:latest
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - API_URL=http://localhost:8080
    expose:
      - 3000
      - 3001
    networks:
      priros_local_network:
    command: ["sh","-c","pnpm dev"]

networks:
  priros_local_network:
    external: true